snd-soc-apple-mca-y	:= mca.o

obj-$(CONFIG_SND_SOC_APPLE_MCA)	+= snd-soc-apple-mca.o
obj-$(CONFIG_SND_SOC_APPLE_NANO7) += nano7-audio.o
obj-$(CONFIG_SND_SOC_APPLE_CS42L81_SPI) += cs42l81-spi.o
obj-$(CONFIG_SND_SOC_APPLE_S5L8740_I2S) += s5l8740-i2s.o
